export const locations = [
  {
    id: 1,
    city: "Delhi",
    country: "India",
    image: "/images/locations/delhi.webp",
    projects: 46,
    residences: 1290,
    price: "$1.2M+",
    x: 67,
    y: 43,
  },
  {
    id: 2,
    city: "Chandigarh",
    country: "India",
    image: "/images/locations/Chandigarh.webp",
    projects: 31,
    residences: 820,
    price: "$2.4M+",
    x: 48,
    y: 25,
  },
  {
    id: 3,
    city: "Dehradun",
    country: "India",
    image: "/images/locations/dehradun.webp",
    projects: 54,
    residences: 1600,
    price: "$3.1M+",
    x: 18,
    y: 31,
  },
  {
    id: 4,
    city: "Mumbai",
    country: "India",
    image: "/images/locations/mumbai.webp",
    projects: 28,
    residences: 760,
    price: "$650K+",
    x: 63,
    y: 48,
  },
  {
    id: 5,
    city: "Goa",
    country: "India",
    image: "/images/locations/goa.webp",
    projects: 19,
    residences: 530,
    price: "$1.7M+",
    x: 74,
    y: 56,
  },
  {
    id: 6,
    city: "Noida",
    country: "India",
    image: "/images/locations/noida.webp",
    projects: 22,
    residences: 640,
    price: "$2.2M+",
    x: 46,
    y: 27,
  },
];